data:
  evfile: '/zfs/astrohe/Fermi_Data/weekly/photon/filelist.txt'
  scfile: '/zfs/astrohe/Fermi_Data/mission/spacecraft/lat_spacecraft_merged.fits'
  ltcube: '/zfs/astrohe/ckarwin/Stacking_Analysis/UFOs/NGC_4151_Analysis/MakeLTCube/zmax_105/UFOs_binned_ltcube.fits' 

binning:

  binsz      : 0.08
  npix : 
               - 625
               - 50 
  binsperdec : 10  
  coordsys   : 'GAL'
  proj : 'CAR'

selection:

  emin    : 1000 #MeV
  emax    : 100000 #MeV
  zmax    : 105
  evclass : 128 #P8R3_SOURCE
  evtype  : 3 
  tmin    : 239557417
  tmax    : 611246581 
  glat    : 0
  glon    : 325      
  filter  : null
 
gtlike:

  edisp : True
  irfs : 'P8R3_SOURCE_V2'
  #edisp_disable : ['isodiff']

model:

  src_roiwidth : 15 
  galdiff  : ["/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_2/Gamma_Ray_Maps/Modified_CO12/masked_reprojected_pion_decay_annuli_0_5.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_2/Gamma_Ray_Maps/Modified_CO12/masked_reprojected_pion_decay_annuli_6_9.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_2/Gamma_Ray_Maps/Modified_CO12/masked_reprojected_pion_decay_annuli_10_12.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_2/Gamma_Ray_Maps/Modified_CO12/masked_reprojected_pion_decay_annuli_13_16.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_1/Gamma_Ray_Maps/CO12/masked_reprojected_pion_decay_annuli_0_5.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_1/Gamma_Ray_Maps/CO12/masked_reprojected_pion_decay_annuli_6_9.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_1/Gamma_Ray_Maps/CO12/masked_reprojected_pion_decay_annuli_10_12.fits","/zfs/astrohe/ckarwin/Machine_Learning_GC/Sim_1/Gamma_Ray_Maps/CO12/masked_reprojected_pion_decay_annuli_13_16.fits"]
  #isodiff  : '/zfs/astrohe/ckarwin/Low_Energy_Sources/20_MeV_to_200_MeV/Analysis_Main/Isotropic_Spectrum/extrapolated_iso_P8R3_SOURCE_V2_v1.txt'
  #catalogs : ['3FGL']

fileio:
  usescratch: False
